# Uncomment the next line to define a global platform for your project

react_native_path = '../node_modules/react-native'
platform :ios, '9.0'

target 'example' do

  pod 'Masonry','~> 1.0'
  pod 'FMDB'
  pod 'React', :path => react_native_path, :subspecs => [
    'Core',
    'CxxBridge', 
    'DevSupport',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', 
    'RCTAnimation',
    'RCTLinkingIOS',
    'RCTActionSheet',
    'RCTGeolocation',
    'RCTImage',
    'RCTSettings',
    'RCTVibration',
    'RCTCameraRoll',
  ]
  pod 'yoga', :path => react_native_path + '/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => react_native_path + '/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => react_native_path + '/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => react_native_path + '/third-party-podspecs/Folly.podspec'

end

